services:

  nginx:
    image: nginx:alpine
    container_name: nginx-basic-demo

    ports:
      - "80:80"

    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html:ro

    depends_on:
      - app1
      - app2

  app1:
    build: .

    environment:
      INSTANCE_NAME: app1

    expose:
      - "8080"

  app2:
    build: .

    environment:
      INSTANCE_NAME: app2

    expose:
      - "8080"